name = "example_app"
description = "Shiny new project"
version = "0.0.0"

authors = ["Henrik Harkonen"]
maintainers = ["Henrik Harkonen <heharkon@iki.fi>"]
maintainers-logins = ["heharkon"]

executables = ["example_app"]



[[depends-on]]  # This line was added by `alr with`
cmd_ada = "~0.0.1"  # This line was added by `alr with`
